# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
	${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-st-ota"
BBFILE_PATTERN_meta-st-ota := "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-st-ota = "7"

EULA_FILE_ST:stm32mpcommon = "${LAYERDIR}/conf/eula/${MACHINE}"
EULA_FILE_ST_MD5SUM:stm32mpcommon = "8b505090fb679839cefbcc784afe8ce9"

# Set a variable to get the STM32MP BSP location
STM32MP_BASE = "${LAYERDIR}"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_meta-st-ota = "1"
LAYERSERIES_COMPAT_meta-st-ota = "scarthgap"

# for optee-os-stm32mp dependency
LAYERDEPENDS_meta-st-ota = "core openembedded-layer meta-python"

# OpenSTLinux compatibility version
ST_OSTL_COMPATIBILITY_VERSION_meta-st-ota = "6.2"

DISTRO_FEATURES:append = " rauc "
